name:                blog-hs
version:             0.1.0.0
github:              "mrtstg/blog-hs"
license:             BSD-3-Clause
author:              "Ilya Zamaratskikh"
maintainer:          "mrtstgdev@gmail.com"
copyright:           "2023 Ilya Zamaratskikh"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/mrtstg/blog-hs#readme>

dependencies:
- base >= 4.7 && < 5
- yesod-core
- text == 2.0.2
- directory == 1.3.7.1
- filepath == 1.4.2.2
- parsec == 3.1.16.1
- containers == 0.6.7
- hedis == 0.15.2
- bytestring == 0.11.5.2
- blaze-html
- aeson
- MissingH == 1.6.0.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  blog-hs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-hs

tests:
  blog-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog-hs
