version: '3'
services:
  redis:
    image: redis:7.2.1-alpine
    container_name: redis-dev
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  app:
    profiles: ['app']
    image: blog-hs:latest
    container_name: blog-hs
    hostname: blog
    restart: unless-stopped
    volumes:
      - ../templates:/usr/src/app/templates
    environment:
      DEPTH_LEVEL: 5
      REDIS_HOST: redis
    ports:
      - 3000:3000
