version: '3'
services:
  redis:
    profiles: ['dev', 'dev-app']
    image: redis:7.2.1-alpine
    container_name: redis-dev
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  redis-prod:
    profiles: ['app']
    image: redis:7.2.1-alpine
    container_name: blog-hs-redis
    hostname: redis
    restart: unless-stopped
  app:
    profiles: ['app', 'dev-app']
    image: blog-hs:latest
    container_name: blog-hs
    hostname: blog
    restart: unless-stopped
    volumes:
      - ../templates:/usr/src/app/templates
      - ../db.db:/usr/src/app/db.db
      - ../robots.txt:/usr/src/app/robots.txt
    environment:
      DEPTH_LEVEL: 5
      REDIS_HOST: redis
      DB_PATH: db.db
      SITE_HOST: "http://localhost:3000"
      ROBOTS_TXT_PATH: "./robots.txt"
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: 5
